(rule
 (target todo_schema.ml)
 (deps ../contracts/Todo.cyrograf)
 (action (write-file todo_schema.ml "let source = {|%{read:../contracts/Todo.cyrograf}|}")))

(library
 (name todo_app)
 (modules model rpc todo_schema)
 (libraries kom demo_contracts yojson))

(executable
 (name backend)
 (modules backend)
 (libraries todo_app))
